export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  HOSPITAL_ADMIN = 'HOSPITAL_ADMIN',
  DOCTOR = 'DOCTOR',
  PATIENT = 'PATIENT',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
  PREFER_NOT_TO_SAY = 'PREFER_NOT_TO_SAY',
}

export enum SessionStatus {
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum NoteStatus {
  DRAFT = 'DRAFT',
  AI_GENERATED = 'AI_GENERATED',
  DOCTOR_REVIEWED = 'DOCTOR_REVIEWED',
  FINALIZED = 'FINALIZED',
}

export enum SyncStatus {
  PENDING = 'PENDING',
  SYNCED = 'SYNCED',
  FAILED = 'FAILED',
}

export enum Dialect {
  NIGERIAN_ENGLISH = 'NIGERIAN_ENGLISH', // legacy
  YORUBA_ACCENTED = 'YORUBA_ACCENTED',
  HAUSA_ACCENTED = 'HAUSA_ACCENTED',
  IGBO_ACCENTED = 'IGBO_ACCENTED',
  ENGLISH = 'ENGLISH',
  PIDGIN = 'PIDGIN',
}

export enum AuditAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  VIEW_NOTE = 'VIEW_NOTE',
  EDIT_NOTE = 'EDIT_NOTE',
  FINALIZE_NOTE = 'FINALIZE_NOTE',
  CREATE_SESSION = 'CREATE_SESSION',
  START_SESSION = 'START_SESSION',
  END_SESSION = 'END_SESSION',
  CREATE_PATIENT = 'CREATE_PATIENT',
  CREATE_DOCTOR = 'CREATE_DOCTOR',
  DELETE_USER = 'DELETE_USER',
  GENERATE_TTS = 'GENERATE_TTS',
}
