export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-screen bg-[#030c0b] relative overflow-hidden flex">

      {/* ── Background atmosphere ── */}
      <div className="absolute inset-0 pointer-events-none select-none">
        {/* Primary glow — top left */}
        <div className="absolute -top-1/4 -left-1/4 w-3/4 h-3/4 rounded-full bg-[#237874] opacity-[0.12] blur-[140px]" />
        {/* Secondary glow — bottom right */}
        <div className="absolute -bottom-1/4 right-0 w-1/2 h-1/2 rounded-full bg-[#1e615e] opacity-[0.08] blur-[120px]" />
        {/* Dot grid */}
        <div
          className="absolute inset-0 opacity-[0.035]"
          style={{
            backgroundImage: 'radial-gradient(circle at 1px 1px, rgba(255,255,255,0.8) 1px, transparent 0)',
            backgroundSize: '36px 36px',
          }}
        />
        {/* Horizontal rule accents */}
        <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-white/10 to-transparent" />
        <div className="absolute bottom-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-white/5 to-transparent" />
      </div>

      {/* ── Left panel — hero content ── */}
      <div className="hidden lg:flex lg:flex-1 flex-col justify-between px-14 xl:px-20 py-12 relative z-10 max-w-3xl">

        {/* Logo */}
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg border border-[#2e9690]/40 bg-[#2e9690]/10 flex items-center justify-center">
            <svg className="h-4 w-4 text-[#4db0a8]" fill="currentColor" viewBox="0 0 24 24">
              <path d="M12 15c1.66 0 3-1.34 3-3V6c0-1.66-1.34-3-3-3S9 4.34 9 6v6c0 1.66 1.34 3 3 3z" />
              <path d="M17 12c0 2.76-2.24 5-5 5s-5-2.24-5-5H5c0 3.53 2.61 6.43 6 6.92V21h2v-2.08c3.39-.49 6-3.39 6-6.92h-2z" />
            </svg>
          </div>
          <span className="font-bold text-white text-lg tracking-tight">Meditir</span>
        </div>

        {/* Main hero */}
        <div className="max-w-lg">
          {/* Eyebrow tag */}
          <div className="inline-flex items-center gap-2 border border-[#2e9690]/30 bg-[#2e9690]/10 rounded-full px-3.5 py-1.5 mb-8">
            <span className="w-1.5 h-1.5 rounded-full bg-[#4db0a8] animate-pulse" />
            <span className="text-[#7dccc4] text-xs font-medium tracking-widest uppercase">
              AI Clinical Documentation
            </span>
          </div>

          <h1 className="text-5xl xl:text-6xl font-bold text-white leading-[1.08] tracking-tight mb-6">
            Clinical notes
            <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#4db0a8] to-[#7dccc4]">
              at the speed
            </span>
            <br />
            of care.
          </h1>

          <p className="text-[#6b8f8d] text-base leading-relaxed mb-10 max-w-md">
            Meditir captures your consultations in real time, understands Nigerian dialects, and generates structured SOAP notes — so you stay focused on the patient in front of you.
          </p>

          {/* Feature list */}
          <div className="space-y-3.5">
            {[
              'Real-time transcription — Nigerian English, Yoruba, Hausa, Igbo',
              'SOAP notes generated by Claude AI in under 30 seconds',
              'Offline mode — transcriptions sync automatically',
              'Multi-role: Doctors, Admins & Patients in one platform',
            ].map((feat) => (
              <div key={feat} className="flex items-start gap-3">
                <div className="w-5 h-5 rounded-md border border-[#2e9690]/40 bg-[#2e9690]/10 flex items-center justify-center shrink-0 mt-0.5">
                  <svg className="h-2.5 w-2.5 text-[#4db0a8]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" />
                  </svg>
                </div>
                <span className="text-[#8aa8a6] text-sm leading-relaxed">{feat}</span>
              </div>
            ))}
          </div>

          {/* Stats row */}
          <div className="mt-12 pt-8 border-t border-white/[0.06] flex gap-10">
            {[
              { value: '< 30s', label: 'Note generation' },
              { value: '4', label: 'Nigerian dialects' },
              { value: '100%', label: 'Offline-capable' },
            ].map((s) => (
              <div key={s.label}>
                <p className="text-2xl font-bold text-white tracking-tight">{s.value}</p>
                <p className="text-xs text-[#3d6462] mt-0.5 font-medium">{s.label}</p>
              </div>
            ))}
          </div>
        </div>

        <p className="text-[#2a4442] text-xs tracking-wide">
          © {new Date().getFullYear()} Meditir · Built for healthcare in Nigeria
        </p>
      </div>

      {/* ── Vertical divider ── */}
      <div className="hidden lg:block w-px bg-gradient-to-b from-transparent via-white/[0.07] to-transparent relative z-10 shrink-0" />

      {/* ── Right panel — auth form ── */}
      <div className="flex-1 flex items-center justify-center px-6 py-12 relative z-10 lg:max-w-[480px] xl:max-w-[520px]">
        <div className="w-full max-w-sm">
          {/* Mobile logo */}
          <div className="flex items-center gap-2.5 mb-10 lg:hidden">
            <div className="w-7 h-7 rounded-lg border border-[#2e9690]/40 bg-[#2e9690]/10 flex items-center justify-center">
              <svg className="h-3.5 w-3.5 text-[#4db0a8]" fill="currentColor" viewBox="0 0 24 24">
                <path d="M12 15c1.66 0 3-1.34 3-3V6c0-1.66-1.34-3-3-3S9 4.34 9 6v6c0 1.66 1.34 3 3 3z" />
                <path d="M17 12c0 2.76-2.24 5-5 5s-5-2.24-5-5H5c0 3.53 2.61 6.43 6 6.92V21h2v-2.08c3.39-.49 6-3.39 6-6.92h-2z" />
              </svg>
            </div>
            <span className="font-bold text-white text-base tracking-tight">Meditir</span>
          </div>
          {children}
        </div>
      </div>

    </div>
  );
}
